### PR TITLE
ADDED EQUILLIBRIUM POINT AND SUBARRAY WITH GIVEN SUM

### PR DESCRIPTION
**Pull request by Suvarna221B**

### CODE REVIEW

**Review by GauravWalia19 — CHANGES_REQUESTED** [review]
Please add the kadane algorithm in this PR which the main program according to issue.

**Review by GauravWalia19 — CHANGES_REQUESTED** [review]
Please resolve merge conflicts with the README file

**Review by GauravWalia19 — APPROVED** [review]

**Comment by Suvarna221B** [comment]
can you please put hacktoberfest accepted label

**Comment by GauravWalia19** [comment]
The PR is already approved so it will be accepted

**Pull request merged**
