### PR TITLE
Half_Reverse_Pyramid

### PR DESCRIPTION
**Pull request by bhaveshjakhar**
HALF PYRAMID of stars

### CODE REVIEW

**Review by GauravWalia19 — CHANGES_REQUESTED** [review]
Please update the README and add your algorithm under right section.

**Comment by bhaveshjakhar** [comment]
Done, Uploaded the Readme file And also added the file to the desired folder.

**Review by GauravWalia19 — CHANGES_REQUESTED** [review]
Remove the duplicate file **HALF_reverse_PYRAMID.py**

**Comment by bhaveshjakhar** [comment]
> 
> 
> Remove the duplicate file **HALF_reverse_PYRAMID.py**

Removed Duplicate file, Done

**Comment by bhaveshjakhar** [comment]
Please check.

**Review by GauravWalia19 — APPROVED** [review]

**Pull request merged**
