### PR TITLE
Vanilla js

### PR DESCRIPTION
**Pull request by juligaioso**
Binary Search in VanillaJS

### CODE REVIEW

**Comment by AlbericoD** [comment]
awesome @juligaioso

**Comment by juligaioso** [comment]
@GauravWalia19  i don't understand

**Comment by juligaioso** [comment]
@GauravWalia19 i don't understand because u don't aceppt the pr

**Comment by GauravWalia19** [comment]
This algorithm is already present. Please create a issue for the algorithm you want to add. We will review asap.

**Pull request closed without merging**
