### PR TITLE
Pattern_rhombus_by-python

### PR DESCRIPTION
**Pull request by zarasingh199**
Using logic of language.

### CODE REVIEW

**Review by GauravWalia19 — CHANGES_REQUESTED** [review]
Please update the README i.e add your algorithm in the right section

**Comment by zarasingh199** [comment]
Please check I updated Readme as well as the file at desired folder.

**Review by GauravWalia19 — CHANGES_REQUESTED** [review]
Remove the rhombus_patt duplicate file from the PR

**Comment by zarasingh199** [comment]
> Remove the rhombus_patt duplicate file from the PR

Please check it now, I have removed the previous file.

**Comment by zarasingh199** [comment]
> Remove the rhombus_patt duplicate file from the PR

@GauravWalia19  please check

**Review by GauravWalia19 — APPROVED** [review]

**Pull request merged**
