### PR TITLE
subsequence of a sequence

### PR DESCRIPTION
**Pull request by PreekshitChandel**
find subsequence of a sequence

### CODE REVIEW

**Comment by GauravWalia19** [comment]
Please create a issue for this with HacktoberFest20 template

**Review by GauravWalia19 — CHANGES_REQUESTED** [review]
Please update the readme with the algorithm you are adding

**Comment by PreekshitChandel** [comment]
okay

**Comment by PreekshitChandel** [comment]
done

**Comment by GauravWalia19** [comment]
Please check your PR and resolve the merge conflicts

**Comment by PreekshitChandel** [comment]
i have resolved it , please check

**Review by GauravWalia19 — APPROVED** [review]

**Pull request merged**
